-- Generated by tools/pole_geometry.py. Do not edit by hand.
--
-- Wire attachment points measured from the pole meshes themselves, so
-- copper and signal wires terminate on the drawn insulators instead of
-- floating above them. Regenerate after changing the pole model.
return {
  ["field-pole"] = {
    {
      wire = {copper = {0, -1.9405}, red = {-0.53, -1.9405}, green = {0.53, -1.9405}},
      shadow = {copper = {1.3963, 1.2452}, red = {0.8663, 1.2452}, green = {1.9263, 1.2452}}
    },
    {
      wire = {copper = {0, -1.9405}, red = {0, -2.3343}, green = {0, -1.5466}},
      shadow = {copper = {1.3963, 1.2452}, red = {1.3963, 0.8513}, green = {1.3963, 1.639}}
    },
    {
      wire = {copper = {0, -1.9405}, red = {0.53, -1.9405}, green = {-0.53, -1.9405}},
      shadow = {copper = {1.3963, 1.2452}, red = {1.9263, 1.2452}, green = {0.8663, 1.2452}}
    },
    {
      wire = {copper = {0, -1.9405}, red = {0, -1.5466}, green = {0, -2.3343}},
      shadow = {copper = {1.3963, 1.2452}, red = {1.3963, 1.639}, green = {1.3963, 0.8513}}
    },
  },
}
