"""Stable 0.2 campaign UI/setting prose, consumed by generate_locale.py."""

def add_campaign_locale(put):
    groups = {
        'entity-name': {'sn-lander':'Stranded expedition lander','sn-bloomback':'Bloomback grazer','sn-bloom-nest':'Symbiotic bloom garden'},
        'entity-description': {
            'sn-lander':'Your one-way landing craft. Recover the shared emergency cargo and defend your first restoration stations. No orbital engine remains: build and launch a Nauvis rocket. After the first launch the hull can be salvaged. One cargo grant per force, never per reconnect.',
            'sn-bloomback':'A former native brood organism reshaped by a restored biosphere. Its flowering carapace shelters a peaceful grazer. Friendly to every force, with no attack damage or territorial expansion.',
            'sn-bloom-nest':'A former brood nest or worm colony, now a permanent flowering habitat. Symbiosis preserves these living spaces instead of clearing them for more factory floor.'},
        'sn-axis': {'smog':'Planetary pollution','hotspot':'Surveyed peak pollution'},
        'virtual-signal-name': {'sn-smog-total':'Planetary pollution inventory','sn-smog-local':'Local chunk pollution'},
        'sn-gui': {
            'air-survey':'Air & natives',
            'ui-error':'[Second Nature] The dashboard could not open. Your factory is still running. Please report the Second Nature dashboard line from factorio-current.log.',
            'footer':'Build a factory. Give life a second chance.   /   v0.2.0 · stable',
            'mature':'Self-sustaining. Keep every axis ≥ 90, toxicity ≤ 8, total pollution ≤ 500 and surveyed hotspots ≤ 10. Maintain beacon shipments.',
            'operation-rule':'Only completed recipes earn work. Soil and biodiversity gains require local pollution ≤ 10. Air/thermal treatment, detoxification and sample production still work in dirty air.',
            'resistance-disabled':'Scripted restoration raids are disabled by settings or peaceful mode. Proximity combat and scenario diplomacy still apply.',
            'network-description':'Research Second Nature, reach stage 5 on all five worlds, and keep one of YOUR force’s beacons on each completing cycles at least every 90 seconds for 10 uninterrupted minutes. Every axis ≥ 90; toxicity ≤ 8; measured total pollution ≤ 500; completed hotspot survey ≤ 10. Shared ecology, force-specific logistics.'},
        'sn-air': {
            'intro':'The global inventory covers the entire surface, including pollution-only engine chunks outside generated terrain—not just your factory. Totals refresh roughly every 10 seconds. The bounded hotspot survey covers fully generated chunks; its peak includes newly detected hotspots. The local reading follows your current location.',
            'total':'Global inventory: __1__ units · Trend: __2__ / minute · Inventory / generated chunk: __3__\nFinal planetary limit: __4__ total units, with no surveyed chunk above 10.',
            'survey':'Generated chunks: __1__ · Hot chunks: __2__ · Surveyed peak: __3__\nSurvey: __4__ · Total reading age: __5__ seconds',
            'complete':'complete pass available','pending':'pending a complete pass; stage 5 is locked',
            'local':'At your position on __1__: __2__ pollution/spore units · Nauvis brood suppression: __3__%',
            'overlay-off':'Show local smog overlay · Ctrl + Shift + P','overlay-on':'Hide local smog overlay · Ctrl + Shift + P',
            'legend':'Overlay: GREEN ≤ 10, suitable for life. AMBER > 10, planting blocked. MAGENTA ≥ 200, heavy contamination that suppresses Nauvis restoration raids. This is a 5 × 5 chunk local survey; use the map’s native pollution layer for a wider view. Pollution does not grant immunity to proximity combat or retaliation.'},
        'sn-native': {
            'explanation':'After Nauvis stays fully restored and pollution-clean for two minutes, choose its permanent native future. Symbiosis reshapes biters and spitters into gentle Bloombacks, and nests/worms into flowering gardens. Eradication removes those populations and frees their space. Both end scripted Nauvis raids; Gleba and demolishers are unchanged. In multiplayer an administrator decides for the shared planet.',
            'symbiosis':'Choose symbiosis','eradication':'Choose eradication',
            'waiting':'Native future: undecided. Restore Nauvis to stage 5 and hold clean conditions for two minutes.',
            'not-ready':'[Second Nature] Restore Nauvis completely and hold clean conditions for two minutes before deciding.',
            'admin-only':'[Second Nature] The native choice affects the entire shared planet. A multiplayer administrator must confirm it.',
            'confirm-symbiosis':'PERMANENT PLANET-WIDE CHOICE: turn native populations into peaceful flowering life. Converted gardens occupy their old habitat. This choice cannot be reversed. Confirm symbiosis?',
            'confirm-eradication':'PERMANENT PLANET-WIDE CHOICE: remove Nauvis biters, spitters, nests and worms, including future discovered colonies. This choice cannot be reversed. Confirm eradication?',
            'confirm-button':'Confirm permanent choice','cancel-button':'Cancel',
            'chosen-symbiosis':'[Second Nature] NAUVIS / Symbiosis chosen. Native populations are being reshaped into Bloombacks and flowering gardens. Future discovered colonies inherit this choice.',
            'chosen-eradication':'[Second Nature] NAUVIS / Eradication chosen. Native colonies are being removed. Future discovered colonies inherit this choice.',
            'resolved-symbiosis':'Native future: SYMBIOSIS · __1__ organisms/colonies converted so far. The bounded sweep continues.',
            'resolved-eradication':'Native future: ERADICATION · __1__ organisms/colonies removed so far. The bounded sweep continues.'},
        'sn-campaign': {
            'briefing':'[Second Nature] LAST LANDING\nThe descent engine is spent. No forests. No fish. Only exhausted earth, legacy smog and the broods that consumed it.\nYour lander holds shared emergency cargo; two loaded turrets guard the camp. Build power and a factory, then a rocket—there is no free ride back to orbit.\nPollution soothes the Nauvis broods, but suffocates new life. Clean industry will wake them. Press Shift + T for the mission, air survey and field guide.',
            'landing-pan':'LAST LANDING / Engine spent. Recover the cargo. Restore Nauvis.',
            'orbit-restored':'[Second Nature] A Nauvis rocket has launched. Orbital access is restored; the lander hull can now be salvaged.',
            'mission-stranded':'MISSION / Stranded on Nauvis. Emergency cargo is in the lander. Build and launch a rocket to restore orbital access; the lander has no launch function.',
            'mission-orbit':'MISSION / Orbital access restored. The lander hull is salvageable. Continue the five-world restoration campaign.',
            'mission-existing':'MISSION / Existing save or custom scenario. No replacement landing, free cargo or retroactive world sterilization is applied.'},
        'map-gen-preset-name': {'sn-last-landing':'Second Nature / Last Landing','sn-brood-frontier':'Second Nature / Brood Frontier','sn-quiet-reclamation':'Second Nature / Quiet Reclamation'},
        'map-gen-preset-description': {
            'sn-last-landing':'Intended stable campaign: stranded lander, emergency cargo, loaded defenses, tree- and fish-free Nauvis, legacy smog and restoration-driven brood resistance. Roomy starting area and 150% ore richness. Keep Desolate landing and Pollution-fed broods enabled in Mod settings.',
            'sn-brood-frontier':'The same desolate expedition with larger, denser native colonies and a smaller starting area. Pollution is a defensive crutch, not a route to a living world.',
            'sn-quiet-reclamation':'A desolate ecological engineering campaign in peaceful mode. The landing, pollution cleanup, industrial loops and native endgame choice remain, but scripted ecological raids are disabled.'},
        'mod-setting-name': {
            'sn-desolate-start':'Desolate Nauvis landing','sn-legacy-smog':'Legacy smog per new Nauvis chunk',
            'sn-biter-metabolism':'Pollution-fed Nauvis broods','sn-menu-background':'Last Landing main-menu illustration',
            'sn-native-fate':'Native fate after full Nauvis restoration'},
        'mod-setting-description': {
            'sn-desolate-start':'Default on. New freeplay starts with a stranded cargo lander and two loaded turrets. Nauvis generates without trees/fish, and fresh grass becomes barren earth. Existing saves are NOT sterilized or given new cargo. Restart required.',
            'sn-legacy-smog':'Initial real pollution seeded once into each newly generated Nauvis chunk during a desolate campaign. Default 80; 0 disables legacy contamination. Existing saves are not seeded. Once the native future is resolved, newly discovered regions no longer introduce this ancient smog.',
            'sn-biter-metabolism':'Default on. Remove pollution-driven attack recruitment from Nauvis biter/spitter nests and disable pollution evolution (Gleban spores unchanged). Restoration raids target recently productive CLEAN machines. Pollution increasingly suppresses those raids; at 200 local units, warnings cancel and tracked waves retreat. Ordinary proximity combat, obstruction and retaliation still exist.',
            'sn-menu-background':'Replace vanilla menu simulations with the original Last Landing illustration. Turn off to retain vanilla or another mod’s menu simulations. Restart required.',
            'sn-native-fate':'Choose in game: a multiplayer administrator confirms the permanent choice in Air & natives after two clean minutes at Nauvis stage 5. Automatic symbiosis/eradication apply the selected policy at that milestone without a dialog. A completed choice cannot be reversed by changing this setting.',
            'sn-native-resistance':'Off disables scripted restoration raids. Balanced respects grace, warning and cooldowns; Relentless is more aggressive. Pollution-fed Nauvis broods is a separate startup rule. Peaceful mode is respected; Gleba retains its native spore mechanics.',
            'sn-living-terrain':'Show machine-local gardens and bounded late-stage Nauvis succession across generated terrain. Smog blocks new growth and browns exposed grass. Native Nauvis water changes between ordinary and green-tinted water without changing its collision/support rules. Paving, foundations, resources, buildings, crop soils, lava and Aquilo ice are protected.'},
        'string-mod-setting': {'sn-native-fate-choose':'Choose in game (recommended)','sn-native-fate-symbiosis':'Automatic symbiosis','sn-native-fate-eradication':'Automatic eradication'},
        'shortcut-name': {'sn-pollution-overlay':'Local smog overlay'},
        'controls': {'sn-toggle-pollution':'Toggle local smog overlay'},
    }
    for group, entries in groups.items():
        for key, value in entries.items():
            put(group, key, value)
    put('sn-planet', 'nauvis', 'NAUVIS / Last Landing. No native trees or fish remain in a new campaign. Rebuild from mineral feedstocks and emergency cargo. Clear the legacy smog, defend the machines that bring life back, and decide whether the broods deserve a second nature.')
    put('sn-message', 'welcome', '[Second Nature] Stable 0.2 / Press Shift + T for the field station, Air & natives and your landing mission. Ctrl + Shift + P shows local smog. Begin with stone → silica → glass and Pioneer biology.')
    put('sn-guide', 'text-3', 'NAUVIS / POLLUTION-FED BROODS\nWith the default startup rule, pollution no longer recruits vanilla biter attack parties or drives pollution evolution. Ecological change instead mobilizes real nearby nests against recently productive clean restoration machines. Dirty retorts and forcing towers are never chosen as targets. Proximity combat, walls obstructing a path and retaliation remain possible.\n\nAt 200 pollution units in a target or nest chunk, new warnings are suppressed. Pollution during a warning cancels it. Tracked waves reaching a polluted target turn back; lesser concentrations reduce wave size and effective resistance. This is temporary protection: local soil/biodiversity gains need ≤ 10, and pollution creates ecological debt.\n\nWaves need an existing nest 96–512 tiles away. Warning: 45 seconds. Balanced grace: 20 minutes after first ecological work. Cooldown: eight minutes. At most 40 units and three tracked groups per world. Clean progress also sets a lower bound on the scripted wave’s strength. Clear the perimeter, build defenses or supply pheromone dampeners.\n\nGLEBA / Native spores still behave normally. Scripted ecological resistance is additional; pollution does not pacify pentapods. No invasions are invented on the other three planets. Peaceful mode and resistance Off disable the scripted waves.\n\nDIRTY SHORTCUTS / Pyrolysis and forcing buy throughput or local calm with waste, pollution and toxic debt. They cannot substitute for cleanup. Keep every byproduct moving and close the filter/effluent loop.')
    put('sn-guide', 'topic-6', 'Last Landing, smog and the native future')
    put('sn-guide', 'text-6', 'LAST LANDING\nChoose the Last Landing map preset and keep the default startup settings. Your crippled lander carries metals, coal, stone, circuits, basic production and power equipment, spare ammunition and finite wood. Two preloaded turrets and short wall segments protect the camp. Cargo is shared per force; reconnecting, respawning or updating cannot mint another load. Build and launch a normal Nauvis rocket before leaving for orbit. Afterward the hull can be salvaged.\n\nA BARREN WORLD\nFresh Nauvis chunks contain no trees or fish, with barren earth in place of grass and 80 units of legacy smog per chunk by default. Ores, rocks, cliffs and water remain. The mineral biology bootstrap does not need natural seeds or wood; use your initial poles carefully and develop cultivated wood.\n\nCLEAN AIR IS NOT A COSMETIC\nThe Air & natives tab reports whole-surface pollution, including pollution-only engine chunks, and your actual local chunk. Hotspot coverage counts fully generated terrain. Soil and biodiversity bonuses require local pollution ≤ 10, though blocked recipes still produce their samples/byproducts. Mean global pollution also constrains biodiversity. Stage 5 requires ≤ 500 total pollution and a completed hotspot survey with no chunk above 10. New exploration adds new territory to survey. Four chunks per second are surveyed across all visited worlds; totals refresh roughly every ten seconds.\n\nVISIBLE RECOVERY\nFirst gardens grow around productive machines. At stage 4, safe clean Nauvis ground recovers in bounded strips across generated chunks, with sparse trees. Live broods prevent local succession. Heavy pollution browns grass and discolors native water; cleanup reverses the water tint. Paving, ore, buildings and support tiles remain intact. This is gradual succession, not an instant paint-the-infinite-map command.\n\nNATIVE FUTURE\nHold Nauvis at fully clean stage 5 for two minutes, then confirm symbiosis or eradication. Symbiosis transforms natives into original flowering Bloombacks and gardens, friendly to all forces. Eradication removes natives. The irreversible policy is applied in bounded sweeps, including future discovered colonies. Existing gardens occupy space; eradication frees it. Dirty industry can still degrade either restored biosphere afterward. The separate five-planet network remains the campaign victory.')
    put('sn-guide', 'text-1', '1. Recover the shared emergency cargo from the lander. Set up the drills, furnaces, boiler/steam engines and poles. Keep the two turrets supplied. Your landing craft cannot fly again; ordinary rocket construction is the way back to orbit.\n\n2. Crush stone into silica in your inventory; smelt it into glass. Overhaul red science consumes glass.\n\n3. Research Pioneer biology. Supply the bioreactor with electricity and water: mineral nutrients → pioneer culture → algae. No natural tree or seed is required.\n\n4. Compost algae, produce biochar and living substrate, and build a soil restoration station. Its samples unlock ecology science even when dirty air suppresses its living-soil bonus. Green science also needs compost.\n\n5. Research atmospheric treatment and supply scrubbers. Clear the local smog to ≤ 10 so soil and biodiversity can grow. Buffer spent filters/effluent until reclamation is researched.\n\n6. Add watersheds, dispersers, thermal exchangers and detoxifiers. Clean industry wakes the broods as its pollution blanket disappears. Expand defenses before rapidly greening the perimeter. Check Air & natives and the field station’s support ceilings when progress stalls.')
