"""Ironbound 0.3 player-facing changes; layered onto the established campaign guide."""

def add_expedition_locale(put):
    groups={
      'entity-name':{'sn-lander':'Ironbound expedition lander','sn-field-pole':'Riveted power pole','sn-field-crate':'Mineral-frame equipment crate'},
      'entity-description':{'sn-lander':'An armored atmospheric landing craft with protected cargo storage, standby ventilation and an autonomous maintenance supply. Its atmospheric propulsion cannot reach orbit.'},
      'ammo-category-name':{'sn-induction':'Induction cells'},
      'mod-setting-name':{'sn-expedition-character':'Industrial expedition explorer'},
      'mod-setting-description':{
        'sn-desolate-start':'New freeplay begins with an intact protected craft, shared cargo, four loaded sentries and riveted barricades. Initial Nauvis has no natural trees/fish. Existing saves are not sterilized or given replacement supplies.',
        'sn-expedition-character':'Original feminine adult explorer with a fitted, fully covered industrial suit, armor variations and animated movement/tool/weapon poses. Turn off to keep the vanilla or another mod’s character appearance. This changes graphics, not character inventories/controllers.',
        'sn-restoration-speed':'Scales ecological work and environmental drift. Base 0.3 rates are 30% of the old rapid coefficients; pollution capture is separately 25%. Process-optimization research adds at most 45% to clean work/capture and supported terrain recovery. Does not accelerate recipes, raid timers or the ten-minute victory hold.',
        'sn-living-terrain':'Render slow, time-integrated succession: sparse pioneer patches → grassland → lush ground, with gradual reversal under sustained smog. Habitat condition still simulates if visuals are off. Only mod-grown trees are removed by the new withering tracker; infrastructure, ore, paving, crop soils and Aquilo support remain protected.'},
      'sn-expedition':{
        'efficiency-effect':'Clean restoration/capture and recently supported terrain growth: total +__1__% (bounded).',
        'habitat-status':'Surveyed habitat condition: __1__% / __2__% required on Nauvis.\nYour process optimization: +__3__%. Base recovery is measured in hours, not seconds.',
      },
      'sn-axis':{'habitat':'Surveyed habitat condition'},
      'sn-gui':{
        'footer':'IRONBOUND EXPEDITION / Restore slowly. Defend what survives.   /   v0.3.0 · stable',
        'mature':'Self-sustaining. Keep every axis ≥ 90, toxicity ≤ 8, total pollution ≤ 500 and known hotspots ≤ 10. Nauvis also needs surveyed habitat condition ≥ 80%.',
        'support-hint':'Fitness and real habitat condition are separate. Local air must be clean before living gains work. Terrain develops over sustained time; process-optimization research helps modestly, never instantaneously.'},
      'sn-campaign':{
        'briefing':'[Second Nature] IRONBOUND EXPEDITION\nYour landing craft is intact. Its atmospheric engines cannot carry you to orbit; build a rocket and a space program. The hull remains a permanent, protected camp.\nFour loaded sentries and riveted barricades cover the landing zone. Shared cargo includes materials, field dressings and reloads. Your carbine accepts the ordinary bullet family.\nThere is no starter-wood dependency: riveted poles, mineral-frame crates, metal gun stocks and algal seed preparation all have wood-free routes.\nClean air and ecological work support slow recovery. Sustained pollution can undo it. Press Shift + T for the field guide and habitat survey.',
        'landing-pan':'IRONBOUND / Intact craft. Hostile world. A long recovery ahead.',
        'orbit-restored':'[Second Nature] Orbital access restored. The intact expedition lander remains your protected ground camp; it is never scrapped.',
        'mission-stranded':'MISSION / The lander is intact and permanently protected. Recover shared supplies, establish defenses and build a normal Nauvis rocket. The landing craft has no orbital launch function.',
        'mission-orbit':'MISSION / Orbital access restored. Your intact, protected lander remains a permanent cargo camp.'},
      'sn-native':{
        'waiting':'Native future: undecided. Restore Nauvis, including ≥ 80% surveyed habitat condition, and hold clean stage 5 for two minutes.',
      },
      'map-gen-preset-description':{
        'sn-last-landing':'Ironbound expedition: intact protected craft, four loaded sentries, wood-free starter construction, a stripped Nauvis and hours-scale ecological recovery. Pollution calms broods but slowly kills restored habitat. Roomy starting area and richer ore.',
      },
    }
    for group,entries in groups.items():
        for key,value in entries.items():put(group,key,value)
    put('sn-guide','text-1','1. Recover the lander cargo, establish water/steam power and keep the four sentries loaded. The intact craft remains protected permanently. Orbit still requires a normal rocket.\n\n2. You do not need wood: the small-pole recipe uses iron sticks, cable and stone; the former wooden chest uses mineral-composite stocks. Stocks are hand-formed from iron and stone. Shotguns use those stocks too.\n\n3. Hand-crush stone into silica and smelt glass. Research Pioneer biology: mineral nutrients → cultures → algae, without natural seeds.\n\n4. Compost algae into substrate and biofilm. Soil stations still make ecological samples in dirty air, even when their living bonus is blocked. Algal biomass replaces wood in pioneer seed mix. Timber remains an optional renewable product.\n\n5. Supply scrubbers and clear local pollution to ≤ 10. Capture is deliberately slower than in 0.2; maintain multiple machines and close the filter/effluent loop.\n\n6. Research Frontier defense for replacement sentries, carbines, armor and field dressings. Basic expedition magazines and barricades are hand-craftable from the start.\n\n7. Upgrade through electrical defense and late bastion doctrine. Research ecological process optimization for bounded +15%, +30%, then +45% clean-work/capture and terrain-growth bonuses.')
    put('sn-guide','topic-6','Ironbound: slow recovery, arms and the native future')
    put('sn-guide','text-6','INTACT EXPEDITION\nThe new lander is not a crash site. It is never mineable or destructible in normal play, even after a rocket launch. Older surviving landers gain the same protection on upgrade. Cargo/defenses are still granted once per force; upgrading cannot mint a second load.\n\nA COMPLETE WOOD-FREE START\nIron/stone composite stocks replace wood in starter crates and shotguns. Riveted poles use iron sticks, cable and stone. Pioneer seed mix uses cultivated algae. Wood composting and wood processing remain optional biological routes; they do not gate initial power or defense. Field dressings replace unavailable wild fish as a craftable healing consumable.\n\nDEFENSE TIERS\nEarly: carbine, improved bullet magazines, field suit, riveted sentries and barricades. Mid: battery-fed induction rifle, capacitor arc turrets, composite walls and six-by-six modular expedition armor. Late: dense-core lance weapons, bastion turrets, ten-by-ten armor and powered biosphere shields. Lasers and shields need energy; guns need ammo; line weapons can hurt your factory.\n\nHOURS, NOT A PAINTBRUSH\nBase ecological gains/drift use 30% of the old rapid coefficients; physical capture uses 25%. Recipes still run at their declared speeds and produce real samples/waste. At ideal conditions, a bare patch needs roughly three hours of supported local time to approach full habitat condition. Research increases that recovery rate by at most 45% (about 31% less ideal time). Real campaign time also includes technology, power, logistics, cleanup and map coverage.\n\nSUSTAINED CHANGE\nClean air plus productive restoration supports slow recovery. At living stage the habitat can sustain growth naturally. Sparse patches become dry grass, then meadow, then lush ground and sparse forests. Sustained heavy pollution builds soil stress over about twenty minutes and degrades mature habitat over roughly two hours. Mod-grown trees wither; protected infrastructure and player plantings are not erased. Mild pollution acts more slowly. Sampling is bounded and conservative across large worlds.\n\nTHE FINAL CHOICE\nNauvis stage 5 requires every fitness axis ≥ 90, toxicity ≤ 8, total pollution ≤ 500, known sampled hotspots ≤ 10, and surveyed habitat condition ≥ 80%. The habitat value is a sampled ecological condition, not a claimed exact percentage of painted tiles. Hold readiness for two minutes, then confirm symbiosis or eradication. The irreversible policy handles moving and future natives. Other planets remain unchanged; the five-world beacon network is still the campaign victory.')
